rootUrl: http://127.0.0.1:8080/components/vaadin-dialog/test/visual/
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "60"
      platform: "Windows 10"
