/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-dialog-draggable-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {DialogDraggableMixin};

declare function DialogDraggableMixin<T extends new (...args: any[]) => {}>(base: T): T & DialogDraggableMixinConstructor;

interface DialogDraggableMixinConstructor {
  new(...args: any[]): DialogDraggableMixin;
}

export {DialogDraggableMixinConstructor};

interface DialogDraggableMixin {
  ready(): void;
}
